# themes from https://github.com/alacritty/alacritty-theme

general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal.shell]
program = "/usr/bin/zsh"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "C"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0
