export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

TERM=xterm-256color
source $ZSH/oh-my-zsh.sh

alias cat='bat'
alias ls='eza -lh --group-directories-first --icons'
alias lsa='ls -a'
alias lt='eza --tree --level=2 --long --icons --git'
alias lta='lt -a'
alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
alias n='nvim'

source <(fzf --zsh)
HISTFILE=~/.history
HISTSIZE=10000
SAVEHIST=50000
setopt appendhistory
eval "$(zoxide init zsh)"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/home/roger/.lmstudio/bin"
# End of LM Studio CLI section

